export interface IUnidadSimple {
    id: number,
    id_categoria: string,
    numero_topografico: string,
    nT_numerocasetes: number,
    nT_numerocinta: number,
    duracion: string,
    soporte: string,
    ie_casete: string,
    ie_cajaprotectora: string,
    alcance_contenido: string,
    dept_toponimicos: string,
    dept_onomasticos: string,
    dept_cronologicos: string,
    dept_otros: string,
    dept_tipoDRegistro: string,
    lengua: string,
    condiciones_acceso: string,
    existencia_localizacion_copias: string,
    unidades_descripcion_asociada: string,
    documentos_asociados: string,
    notas: string,
    notas_control_interno: string,
    fechaDRegistro: string,
    fechaDUltimaAct: string,
    Descriptores: string
}